<?php

namespace Database\Seeders;

use App\Models\SteamAchievement;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class SteamAchievementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Games are seeded in the exact order of the source list (id 1 = Desolate ...
        // id 80 = Hitman Absolution). tags and date_completed are placeholders the owner
        // fills in manually later; only the parenthetical entries carry a note.
        SteamAchievement::insert([
            [
                'game_name' => 'Desolate',
                'tags' => null,
                'date_completed' => '2021-07-05',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'A Plague Tale: Innocence',
                'tags' => null,
                'date_completed' => '2021-09-26',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'The Sinking City',
                'tags' => null,
                'date_completed' => '2022-09-22',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'This War of Mine',
                'tags' => 'bad review (dlc)',
                'date_completed' => '2022-10-23',
                'notes' => 'Originally completed on Oct. 23, 2022 but a new DLC was released in 2024, adding new achievements. Completed again on April 30, 2025',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Resident Evil 5',
                'tags' => null,
                'date_completed' => '2022-12-04',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Vampyr',
                'tags' => null,
                'date_completed' => '2022-12-06',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Detroit: Become Human',
                'tags' => null,
                'date_completed' => '2022-12-24',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Sleeping Dogs: Definitive Edition',
                'tags' => null,
                'date_completed' => '2023-01-17',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Ravenous Devils',
                'tags' => 'good review',
                'date_completed' => '2023-02-05',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Cloudpunk',
                'tags' => 'good review',
                'date_completed' => '2023-03-19',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Heavy Rain',
                'tags' => null,
                'date_completed' => '2023-03-23',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Spec Ops: The Line',
                'tags' => null,
                'date_completed' => '2023-04-07',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Stray',
                'tags' => 'good review',
                'date_completed' => '2023-04-20',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Mark of the Ninja: Remastered',
                'tags' => null,
                'date_completed' => '2023-05-11',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'RONIN',
                'tags' => 'bad review',
                'date_completed' => '2023-05-14',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Tavern Master',
                'tags' => null,
                'date_completed' => '2023-05-25',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'A Plague Tale: Requiem',
                'tags' => null,
                'date_completed' => '2023-06-01',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Grand Theft Auto IV: The Complete Edition',
                'tags' => null,
                'date_completed' => '2023-07-08',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Coffee Talk',
                'tags' => 'good review',
                'date_completed' => '2023-07-10',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Cassette Beasts',
                'tags' => 'over 100 achievements',
                'date_completed' => '2023-08-14',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Battle Royale Tycoon',
                'tags' => null,
                'date_completed' => '2023-09-03',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Travellin Cats Hidden in Paris',
                'tags' => 'free to own,good review,over 100 achievements',
                'date_completed' => '2023-09-12',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Unheard - Voices of Crime',
                'tags' => null,
                'date_completed' => '2023-09-15',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Party Hard',
                'tags' => 'good review',
                'date_completed' => '2023-09-18',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Cosmic Star Heroine',
                'tags' => 'good review',
                'date_completed' => '2023-09-25',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Counter-Strike 2',
                'tags' => 'good review (before completion),free to play',
                'date_completed' => '2023-10-01',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'VA-11 Hall-A: Cyberpunk Bartender Action',
                'tags' => 'good review',
                'date_completed' => '2023-10-12',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Intravenous',
                'tags' => null,
                'date_completed' => '2023-10-14',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Pentiment',
                'tags' => null,
                'date_completed' => '2023-10-27',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'MURDERED: SOUL SUSPECT',
                'tags' => 'good review',
                'date_completed' => '2023-11-13',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'As Dusk Falls',
                'tags' => null,
                'date_completed' => '2023-11-26',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Quantum Break',
                'tags' => 'good review',
                'date_completed' => '2023-12-01',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'JUSTICE SUCKS',
                'tags' => null,
                'date_completed' => '2023-12-02',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Bright Memory',
                'tags' => null,
                'date_completed' => '2023-12-06',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Kingdom Come: Deliverance',
                'tags' => 'good review',
                'date_completed' => '2024-03-02',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'This Bed We Made',
                'tags' => 'bad review',
                'date_completed' => '2024-03-16',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'EDENGATE: The Edge of Life',
                'tags' => null,
                'date_completed' => '2024-03-28',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'What Remains of Edith Finch',
                'tags' => null,
                'date_completed' => '2024-03-30',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'The Forgotten City',
                'tags' => null,
                'date_completed' => '2024-03-31',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'RUINER',
                'tags' => null,
                'date_completed' => '2024-04-30',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Deadlight Director\'s Cut',
                'tags' => null,
                'date_completed' => '2024-05-31',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Necrobarista',
                'tags' => null,
                'date_completed' => '2024-06-30',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Thief of Thieves: Season One',
                'tags' => null,
                'date_completed' => '2024-07-05',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Subsurface Circular',
                'tags' => null,
                'date_completed' => '2024-08-04',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Dead Island: Riptide Definitive Edition',
                'tags' => 'free to own',
                'date_completed' => '2024-09-03',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Party Hard 2',
                'tags' => 'bad review',
                'date_completed' => '2024-09-12',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Hatred',
                'tags' => 'good review,received as gift',
                'date_completed' => '2024-09-29',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Twin Mirror',
                'tags' => 'good review',
                'date_completed' => '2024-10-26',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Tales of the Neon Sea',
                'tags' => null,
                'date_completed' => '2024-11-24',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Whispers of a Machine',
                'tags' => 'good review',
                'date_completed' => '2024-12-06',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Kathy Rain: Director\'s Cut',
                'tags' => 'good review',
                'date_completed' => '2024-12-17',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Black Mesa',
                'tags' => 'bad review',
                'date_completed' => '2024-12-30',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Intravenous 2: Mercenarism',
                'tags' => 'free to own, good review',
                'date_completed' => '2025-01-02',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Intravenous 2',
                'tags' => 'good review',
                'date_completed' => '2025-01-12',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Mafia: Definitive Edition',
                'tags' => null,
                'date_completed' => '2025-04-17',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Internet Cafe Simulator',
                'tags' => 'bad review',
                'date_completed' => '2025-05-18',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Internet Cafe Simulator 2',
                'tags' => 'bad review',
                'date_completed' => '2025-05-19',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Mafia II: Definitive Edition',
                'tags' => 'good review',
                'date_completed' => '2025-07-12',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Resident Evil 4 Remake',
                'tags' => 'pre-order',
                'date_completed' => '2025-07-12',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Ultimate Zombie Defense',
                'tags' => 'free to own',
                'date_completed' => '2025-08-03',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'I Am Part-time Worker!!',
                'tags' => null,
                'date_completed' => '2025-08-21',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Dying Light',
                'tags' => 'good review',
                'date_completed' => '2025-08-22',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Scene Investigators',
                'tags' => null,
                'date_completed' => '2025-09-16',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Dying Light: The Beast',
                'tags' => 'free to own,good review',
                'date_completed' => '2025-10-10',
                'notes' => 'Free to own due to pre-ordering Dying Light 2: Stay Human. Originally completed on Oct. 10, 2025 but a new DLC was released a few weeks later, adding new achievements. Completed again on ???',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Dying Light 2: Stay Human',
                'tags' => 'good review (before completion),pre-order',
                'date_completed' => '2025-10-26',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Police Stories',
                'tags' => 'good review',
                'date_completed' => '2025-11-23',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'While We Wait Here',
                'tags' => 'good review',
                'date_completed' => '2025-11-25',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'A TAVERN FOR TEA',
                'tags' => null,
                'date_completed' => '2025-12-21',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'CRISIS CORE –FINAL FANTASY VII– REUNION',
                'tags' => 'good review',
                'date_completed' => '2026-01-11',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'The Dark Pictures Anthology: House of Ashes',
                'tags' => 'received as gift',
                'date_completed' => '2026-03-05',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Squirrel with a Gun',
                'tags' => 'good review',
                'date_completed' => '2026-03-10',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Paranormal Cleanup',
                'tags' => 'good review,over 100 achievements,received as gift',
                'date_completed' => '2026-03-23',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Copycat',
                'tags' => 'good review',
                'date_completed' => '2026-03-26',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'VirtuaVerse',
                'tags' => 'bad review',
                'date_completed' => '2026-03-28',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'INDIKA',
                'tags' => 'good review',
                'date_completed' => '2026-04-03',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Deliver Us The Moon',
                'tags' => 'good review',
                'date_completed' => '2026-04-04',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Burnhouse Lane',
                'tags' => 'bad review',
                'date_completed' => '2026-04-13',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => '1998: The Toll Keeper Story',
                'tags' => 'good review',
                'date_completed' => '2026-05-24',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'ANNO: Mutationem',
                'tags' => null,
                'date_completed' => '2026-05-27',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'game_name' => 'Hitman Absolution',
                'tags' => 'good review',
                'date_completed' => '2026-07-07',
                'notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
